accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('password_reset/', auth_views.LogoutView.as_view(template_name="password_reset.html"), name='password_reset'),
    
    # path('signup/', views.SignUpView.as_view(),
    #     name='signup'),
    # path('signup_success/', views.SignUpSuccessView.as_view(),
    #     name='signup_success'),



]

note/urls.py
from django.urls import path
from . import views
from .views import AnnouncementListView, NotePostLikeView


app_name = 'note'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreateNoteView.as_view(), name='post'),
    path('post_done', views.PostSuccessView.as_view(), name='post_done'),
    path('notes/<int:category>',
        views.CategoryView.as_view(),name = 'notes_cat'),
    path('user-list/<int:user>', views.UserView.as_view(), name = 'user_list'),
    #path('note-detail/<int:pk>', views.NoteDetailView.as_view(), name = 'note_detail'),
    path('note/<int:pk>/', views.NoteDetailView.as_view(), name = 'detail'),
    path('mypage', views.MypageView.as_view(), name = 'mypage'),
    path('note/<int:pk>/delete/', views.NoteDeleteView.as_view(), name = 'note_delete'),
    path('note/edit/<int:pk>/' ,views.NoteUpdateView.as_view(), name= 'edit'),
    path('note/search', views.NoteSearchView.as_view(), name= 'note_search'),
    #path('note/<int:pk>/react/', views.ReactionCreateView.as_view(), name='reaction_form'),
    #path('reaction/<int:pk>/good/', GoodView.as_view(), name='good'),
    path('note/<int:pk>/comment/', views.CommentCreateView.as_view(), name='add_comment'),
    path('announcements/', AnnouncementListView.as_view(), name='announcement_list'),
    path('note/like/<int:pk>/', NotePostLikeView.as_view(), name='notepost_like'),

]   

noteproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views 
#from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    
    # path('', login_required(index_view), name="index"),
    path('admin/', admin.site.urls),
    path('', include('note.urls')),
    # path('', include('accounts.urls')),
    #path('', include('note.urls')),
    path('login/', include('accounts.urls')),
    # path('mypage', include('note.urls')),
    # path('update', include('note.urls')),
    path('', include("django.contrib.auth.urls")),
    path('note/', include('note.urls')),
    # path('reactions/', include('reactions.urls')),


    # path('password_reset/',
    #     auth_views.PasswordResetView.as_view(
    #     template_name = "password_reset.html"),
    #     name ='password_reset'),
    
    # path('password_reset/done/',
    #     auth_views.PasswordResetDoneView.as_view(
    #     template_name = "password_reset_sent.html"),
    #     name ='password_reset_done'),
    
    # path('reset/<uidb64>/<token>',
    #     auth_views.PasswordResetConfirmView.as_view(
    #     template_name = "password_reset_form.html"),
    #     name ='password_reset_confirm'),
    

    # path('reset/done/',
    #     auth_views.PasswordResetCompleteView.as_view(
    #     template_name = "password_reset_done.html"),
    #     name ='password_reset_complete'),

]

# urlpatterns += static(
#     settings.MEDIA_URL,
#     document_root=settings.MEDIA_ROOT
# )


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

reactions/urls.py
from django.urls import path
from .views import NotePostLikeView
# from .views import add_reaction, detail  # インポート修正

app_name = 'reactions'

urlpatterns = [

    path('notepost-like/<int:pk>/', NotePostLikeView.as_view(), name="notepost_like"),
#   path('add_reaction/<int:note_id>/', add_reaction, name='add_reaction'),
#   path('detail/<int:note_id>/', detail, name='detail'),  # インポート修正

]

note/models.py
from django.db import models
from accounts.models import CustomUser
from django.urls import reverse #commetで追加
#from django.contrib.auth.models import CustomUser
# from reactions.models import Reaction


class Announcement(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    

class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=20
    )

    def __str__(self):
        return self.title
    

class NotePost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )

    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )

    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
    )

    comment = models.TextField(
        verbose_name='コメント',
    )

    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to='notes',
        blank=True,
        null=True
    )

    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to='notes',
        blank=True,
        null=True
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    likes = models.ManyToManyField(CustomUser, related_name='notepost_like',  blank=True)
    def number_of_likes(self):
        return self.likes.count()


    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.title
    



class Comment(models.Model):
    post = models.ForeignKey(NotePost, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.text[:50] 
    


class Like(models.Model):
    # いいねに関するフィールド
    post = models.ForeignKey(NotePost, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    


# class Reaction(models.Model):
#      OK = 'OK'
#      COMMENT = 'COMMENT'

#      REACTION_CHOICES = [
#          (OK, '見ました'),
#          (COMMENT, 'コメントあり'),
#      ]
#     reactions = models.ForeignKey('reaction.Reaction', on_delete=models.CASCADE)
#      user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#     note = models.ForeignKey(NotePost, on_delete=models.CASCADE)
#      reaction_type = models.CharField(max_length=20, choices=REACTION_CHOICES)

#      def __str__(self):
#          return f"{self.user.username} reacted {self.reaction_type} to {self.note.title}"

reactions/models.py
# from django.db import models
# # from django.contrib.auth.models import User
# from accounts.models import CustomUser
# from note.models import NotePost
# from django.conf import settings
# from datetime import datetime
# from django.utils import timezone


# class Reaction(models.Model):
#     REACTION_CHOICES = (
#         ('LIKE', 'Like'),
#         ('LOOK', 'Look'),
#         ('COMMENT', 'Comment'),
#     )

#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#     note = models.ForeignKey(NotePost, on_delete=models.CASCADE)
#     reaction_type = models.CharField(max_length=10, choices=REACTION_CHOICES)
#     created_at = models.DateTimeField(default=datetime.now)
    
#     def __str__(self):
#         return f"{self.user.username} - {self.reaction_type}"
#     class Meta:
#         ordering = ['-created_at']

note/forms.py
from django import forms
from django.forms import ModelForm
from .models import NotePost, Comment


class NotePostForm(ModelForm):
    class Meta:
        model = NotePost
        fields = ['category', 'title', 'comment', 'image1', 'image2']
    


class SearchForm(forms.Form):
    query = forms.CharField(label='検索')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']  





# class ReactionForm(ModelForm):
#     class Meta:
#         model = Reaction
#         fields = ['reaction_type']
#         # widgets = {
#         #     'reaction_type': forms.RadioSelect,
#         # }
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['reaction_type'].empty_label = ""

reactions/forms.py
# from django import forms
# from .models import Reaction

# class ReactionForm(forms.ModelForm):
#     class Meta:
#         model = Reaction
#         fields = ['reaction_choices']

note/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden
from django.views import View
from django.views.generic.list import ListView
from django.views.generic import TemplateView, ListView
from django.views.generic import CreateView, DetailView, DeleteView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.db.models import Q 
from .forms import NotePostForm, SearchForm, CommentForm #ReactionForm 
from .models import NotePost, Comment, Announcement  #reaction
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# from reactions.models import Reaction


#from django.db.models.query import QuerySet


class IndexView(ListView):
    template_name ="index.html"
    queryset = NotePost.objects.order_by('-posted_at')
    #extra_context={"form":ReactionForm()}
    paginate_by = 100


class AnnouncementListView(ListView):
    model = Announcement
    template_name = 'announcement_list.html'
    context_object_name = 'announcements'

    def get_queryset(self):
        # 最新の5件のお知らせを取得
        return Announcement.objects.all().order_by('-published_date')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # お知らせの日付をフォーマットして追加
        for announcement in context['announcements']:
            announcement.formatted_date = announcement.published_date.strftime('%Y年%m月%d日')
        return context


class TopPageView(TemplateView):
    template_name = 'top_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # トップページに表示する「いいね」の数を取得
        top_posts = NotePost.objects.all()[:10]  # トップ10の投稿を取得する例

        context['top_posts'] = top_posts  # トップページに表示する投稿
        return context

@method_decorator(login_required, name= 'dispatch')
class CreateNoteView(CreateView):
    form_class = NotePostForm
    template_name = "post_note.html"
    success_url = reverse_lazy('note:post_done')
    
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
    
    
class PostSuccessView(TemplateView):
    template_name = 'post_success.html'


class CategoryView(ListView):
    template_name = 'index.html'
    paginate_by = 15

    def get_queryset(self): 
        category_id = self.kwargs['category']
        categories = NotePost.objects.filter(
        category=category_id).order_by('-posted_at') 
        return categories
    

class UserView(ListView):
    template_name ='index.html'
    paginate_by= 15

    def get_queryset(self):
        print(self.kwargs)
        user_id=self.kwargs["user"]
        user_list=NotePost.objects.filter(
        user=user_id).order_by("-posted_at")
        return user_list
    

class NoteDetailView(DetailView):
    model = NotePost
    template_name ='detail.html'
    context_object_name = 'object'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.object)
        
        liked = False
        if self.object.likes.filter(id=self.request.user.id).exists():
            liked = True
        context['number_of_likes'] = self.object.number_of_likes()
        context['post_is_liked'] = liked
        context['liked_users'] = self.object.likes.all()

        return context
    

class NotePostLikeView(LoginRequiredMixin, View):
    
    def post(self, request, pk):
        post = get_object_or_404(NotePost, id=pk)
        
        # ユーザーが既に「いいね」している場合は、それを取り消す
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            # それ以外の場合は「いいね」を追加
            post.likes.add(request.user)
        return redirect('note:detail', pk=pk)


#commentで追加した12/18
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'

    def form_valid(self, form):
        post = get_object_or_404(NotePost, pk=self.kwargs['pk'])
        form.instance.user = self.request.user
        form.instance.post = post
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('note:detail', kwargs={'pk': self.object.post.pk})
    



class MypageView(ListView):
    template_name ='mypage.html'
    paginate_by = 15
    
    def get_queryset(self):
        queryset = NotePost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        return queryset



class NoteDeleteView(DeleteView):
    model = NotePost
    template_name ='note_delete.html'
    success_url = reverse_lazy('note:mypage')

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    


@method_decorator(login_required, name='dispatch')
class NoteUpdateView(UpdateView):
    model=NotePost
    form_class = NotePostForm
    template_name = "edit.html"
    success_url = reverse_lazy('note:post_done')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class NoteSearchView(ListView):
    model = NotePost
    template_name = 'note_search.html'  
    context_object_name = 'note_list'
    paginate_by = 10

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            if query:
                return NotePost.objects.filter(
                    Q(title__icontains=query) | Q(comment__icontains=query)
                )
        return NotePost.objects.none()
    




# #@method_decorator(login_required, name='dispatch')
#     def detail(request, note_id):
#         note = get_object_or_404(NotePost, pk=note_id)
#         reactions = Reaction.objects.filter(note=note)
#         return render(request, 'detail.html', {'note': note, 'reactions': reactions})


    

# @method_decorator(login_required, name= 'dispatch')
# class ReactionCreateView(CreateView):
#     template_name = "reaction_form.html"
#     model = Reaction
#     form_class = ReactionForm 

#     def form_valid(self, form):
#         postdata = form.save(commit=False)
#         postdata.user = self.request.user
#         postdata.save()
#         reaction_type = self.request.POST.get('reaction_type') 
#         reaction = Reaction.objects.create(user=self.request.user, post=postdata, reaction_type=reaction_type)

#         reaction.save()
#         return super().form_valid(form)

# class GoodView(CreateView):
#     def post(self, request, pk):
#         post = get_object_or_404(ReactionForm, pk=pk)
#         post.good += 1
#         post.save()
#         return redirect('list')

reactions/views.py
# from django.shortcuts import render, redirect, get_object_or_404
# from .models import Reaction
# from .forms import ReactionForm
# from note.models import NotePost


# def add_reaction(request, note_id):
#     if request.method == 'POST':
#         form = ReactionForm(request.POST)
#         if form.is_valid():
#             reaction = form.save(commit=False)
#             reaction.user = request.user
#             reaction.note_id = note_id
#             reaction.save()
#         return redirect('note_detail', note_id=note_id)
#     else:
#         form = ReactionForm()

#     return render(request, 'add_reaction.html', {'form': form})



# def r_detail(request, note_id):
#     note = get_object_or_404(NotePost, pk=note_id)
#     reactions = Reaction.objects.filter(note_id=note_id)
#     form = ReactionForm()
#     return render(request, 'r_detail.html', {'note': note, 'reactions': reactions, 'form': form})

note/templates/add_comment.html
{% extends 'base.html' %}

{% block title %}Add Comment{% endblock %}

{% block content %}
<div class="container">
    <h2>コメント追加</h2>
    <form method="post" action="{% url 'note:add_comment' object.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">コメントする</button>
    </form>
</div>
{% endblock %}

note/templates/announcement_list.html
<h2>重要なお知らせ</h2>
<ul>
{% for announcement in announcements %}
  <li>
    <strong>{{ announcement.formatted_date }}</strong>: {{ announcement.title }}
  </li>
{% empty %}
  <li>現在、お知らせはありません。</li>
{% endfor %}
</ul>

note/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{% block title %}{% endblock %}</title>

    <link rel="icon" type="image/x-icon"
          href={% static 'assets/favicon.ico' %} />
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
  </head>
  <body>
<header>
  <div class="collapse bg-light" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <p class="text-muted">機能
            <br>・記事に対するリアクション機能→確認漏れ防止
            <br>・カテゴリ、投稿者ごとに記事の絞り込みができる
          <br>・検索機能で探したい記事を見つけやすく</p>
        </div>
        <div class="col-sm-8 col-md-7 py-4">
          <h6>MY MENU
          </h6>
          <ul class="list-unstyled">
            {% if user.is_authenticated %} 
            <li><a href="{% url 'note:mypage' %}"
              class="text-gray">マイページ</a></li>
            <li><a href="{% url 'note:index' %}"
              class="text-gray">トップページ</a></li>
            <li><a href="{% url 'accounts:logout' %}"
              class="text-gray">ログアウト</a></li>
              
            {% else %}
            <li><a href="{% url 'accounts:login' %}"
              class="text-gray">ログイン</a></li>

            {% endif %}    
            
            <!-- base.html の一部 -->
            <form method="get" action="{% url 'note:note_search' %}">
            <input type="text" name="query" placeholder="記事を検索">
            <button type="button" class="btn btn-outline-primary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search-heart" viewBox="0 0 16 16">
              <path d="M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z"/>
              <path d="M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z"/>
            </svg></button></form>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-light bg-light shadow-sm">
    <div class="container">
      <a href="{% url 'note:index' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Share Note</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

   <!-- 重要なお知らせのセクションを追加 -->
   <section class="announcements">
    <div class="container py-4">
      <h2 class="h6 ">重要なお知らせ</h6>
      <ul class="list-unstyled">
        {% for announcement in announcements %}
          <li>
            <strong>{{ announcement.published_date }}</strong>: {{ announcement.title }}
          </li>
        {% empty %}
          <li>現在、お知らせはありません。</li>
        {% endfor %}
      </ul>
    </div>
  </section>


{% block contents %}{% endblock %}
</main>

{% if user.is_authenticated %} 
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="{% url 'note:index'%}">Back to top</a>
    </p>
    <p class="mb-1">Share Note is &copy; ***</p>
  </div>     
</footer>
{% else %}
{% endif %}   

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    </body>
</html>

note/templates/edit.html
{% extends 'base.html' %}
{% block title %}Post Edit{% endblock %}
    {% block contents %}
    <br>
    <div class = "container">
        <div class = "row">
            <div class = "col offset-2 ">
                <form method ="post"
                        enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <hr>
                            <button type="submit">更新</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

{% comment %} {% extends 'base.html' %}
{% block title %}Note Edit{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる -->
          <div class="col offset-3">

            <form method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <button class="btn btn-primary my-2"
                      type="submit">編集</button>
              <a href="{% url 'note:note_detail' object.pk %}" 
                class="btn btn-secondary my-2">キャンセル</a>
            </form>
          </dv>
        </dv>
      </dv>
      {% endblock %} {% endcomment %}

note/templates/note_search.html
<!-- article_search.html -->
{% extends 'base.html' %}

{% block contents %}
  <h6>検索結果</h6>
  {% comment %} <form method="get" action="{% url 'note:note_search' %}" class="search-form">
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">検索</button>
  </form> {% endcomment %}

  
    {% if note_list %}
    <div class="note-list">
      {% for note in note_list %}
        <div class="note-card">
          <h3><a href="{% url 'note:detail' note.pk %}">{{ note.title }}</a></h3>
          <p>{{ note.summary }}</p> 
          <span class="note-date">{{ note.posted_at }}</span>
        </div>
      {% endfor %}
    </div>
    {% else %}
    <p>検索条件に一致する記事は見つかりませんでした。</p>
    {% endif %}

{% endblock %}

note/templates/notes_list.html
{% load static %}

{% if user.is_authenticated %}

<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for record in object_list %}
      <div class="col">
        <div class="card shadow-sm">

      {% comment %} {% if record.image1 %}
        <img src="{{ record.image1.url }}"
            class="bd-placeholder-img card-img-top"
            width="100%" height="225">
      {% endif %} {% endcomment %}

          <div class="card-body">
            <p class="card-text">
              {{record.title}}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">

                <button type="button" class="btn btn-sm btn-outline-secondary"
onclick="location.href='{% url 'note:detail' record.pk %}'">
                  View</button>

                <button type="button" class="btn btn-sm btn-outline-secondary"
                onclick="location.href='{% url 'note:notes_cat' category=record.category.id %}'">
                {{record.category.title}}</button>
                
                <div class="card-footer text-muted">
                  <p class="card-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                  </svg> {{ record.number_of_likes }}</p>
                </div>  
                
                {% comment %} <p>✓ {{ record.number_of_likes }}</p> {% endcomment %}
                                 
                  {% csrf_token %}
                  {{form.as_p}}
                </form>
              </div>
              <a href="{% url 'note:user_list' user=record.user.id %}">
                <small class="text-muted">{{record.user.username}}</small>
              </a>
            </div>
          </div>
        </div>
      </div>
{% endfor %}
    </div>
  </div>
</div>

{% else %}

{% endif %}

note/templates/notes_title.html
<!-- タイトルとナビゲーションボタン -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        {% if user.is_authenticated %}
        <h5 class="fw-light"></h5>
        <p class="lead text-muted"></p>
        {% else %}
        {% endif %}
        <p>
          <!-- ナビゲーションボタン -->
          {% if user.is_authenticated %}
         {{user.username}}さんがログイン中です
          <br>
          <a href="{% url 'note:post'%}" class="btn btn-primary my-2">投稿</a>
          <a href="{% url 'accounts:logout'%}" class="btn btn-secondary my-2">ログアウト</a>

          {% else %}
          <a href="{% url 'accounts:login'%}" class="btn btn-primary my-2">ログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>





  {% comment %} <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Note一覧</h1>
        <p class="lead text-muted">検索機能もぜひご活用ください</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Noteを作る</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
        </p>
      </div>
    </div>
  </section>  {% endcomment %}